{
 "title": "APIM APK Agent",
 "description": "This dashboard visualizes key CC apim-apk-agent metrics, including CPU usage, memory consumption, and garbage collector activity. ",
 "tags": [
  "Prometheus",
  "Go",
  "apim-apk-agent"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job", "query": "apim-apk-agent" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(go_info{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\",instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(go_info{job=\"$job\",instance=\"$instance\"}, \"version\", \"\", \"version\")"
    }
   ]
  },
  {
   "title": "Instance Up/Down",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "up{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Available CPUs",
   "type": "stat",
   "description": "Number of available central processing units",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_available_cpu_total{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "description": "This represents the amount of memory of free physical memory in the host (free = total – (used + shared + cached + buffered))",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "os_free_physical_memory_bytes{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Load Average [1 Min]",
   "type": "stat",
   "description": "Represents the current load of CPU in the host system in last minute.",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "os_system_load_average{job=\"$job\",instance=\"$instance\", duration=\"1m\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Represents the CPU load in this process",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "os_system_cpu_load_percentage{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "description": "Represents the current load of CPU in the host system for the last 'x' minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "os_system_load_average{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Load Avg [{{duration}}]"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Percentage memory usage of the system",
   "gridPos": { "h": 7, "w": 20, "x": 2, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(os_used_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"} / os_total_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}) * 100",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Mspan Inuse"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Mspan System"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Mcache Inuse"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Mcache System"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Bucket Hash System"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "GC System"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Other Runtime Allocations"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Heap Allocated"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Heap System"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Heap Idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Heap Inuse"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Heap Released"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Stack Inuse"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Stack System"
    }
   ]
  },
  {
   "title": "Memory Allocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", instance=\"$instance\"}[1m])",
     "legendFormat": "Memory Allocation Rate"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"$job\",instance=\"$instance\"} - go_memstats_frees_total{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Live Objects"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "Rate of number of allocations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"$job\",instance=\"$instance\"}[1m])",
     "legendFormat": "Rate of Objects Allocated"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  }
 ]
}